### PR TITLE
Set default mpi type to conda

### PR DESCRIPTION
**Pull request by andrrizzi**
Ready to be merged.

### CODE REVIEW

**Comment by andrrizzi** [comment]
Does this get automatically pushed to anaconda or do we need to release it through omnia?

**Comment by jchodera** [comment]
I think we have to cut a new release and update the conda recipe.

**Comment by andrrizzi** [comment]
Ok, I've bumped the `setup.py` version. Feel free to merge this when you want me to proceed to create a release and update the `conda-recipes` repo.

**Comment by jchodera** [comment]
Thanks!  I'll bump the `conda-recipes` repo.

**Pull request merged**
